### ISSUE TITLE
Cache results from engines

### ISSUE THREAD

**Issue by blueyed** [peterosterlund2/droidfish#1]
I've noticed that the engine re-calculates outcomes when moving backward/forward while you are analysing a game etc.

I think these results could be cached internally by DroidFish, at least if they are "final" / good enough.
But in case the engine could be fed with some starting point to continue where it was stopped/interrupted before, these could be cached and used for seeding also.

That would result in less computing / battery usage and improve the usability, because the arrows from the suggestions won't jump around so much.

Would that be possible and feasible?

**Comment by peterosterlund2** [comment]
This already happens automatically because how engines handle their transposition table. The reason it can not immediately get back the same result as the last time the position was searched is that the transposition table has a fixed size, so it can not remember everything.
