### ISSUE TITLE
Export-Error

### ISSUE THREAD

**Issue by ChristophHeilmann** [peterosterlund2/droidfish#10]
Hello,

When I tried to export the DroidFish-apk I got errors:

Java not found
Proguard returned with error code 1

<terminated> ECO_Builder [ Ant Builder ] C:\Users\Günter\git\droidfish\droidfish\DroidFish\build_eco.xml

Buildfile: C:\Users\Günter\git\droidfish\droidfish\DroidFish\build_eco.xml

build_eco:
BUILD SUCCESSFUL
Total time: 1 second

Do I have to edit the Eco_Builder in DroidFish Properties?

Christoph

**Comment by aprijal-psrb** [comment]
"Java not found"
Are you already have java in your PATH?

**Comment by peterosterlund2** [comment]
Adding java to PATH probably works, but my intention was that this should not be necessary. I have pushed a fix for this. Please update and try again.
