### ISSUE TITLE
DroidFish 1.64 stopped

### ISSUE THREAD

**Issue by reno-a** [peterosterlund2/droidfish#11]
Hello,
The last version (1.64) don't start on CyanogenMod 13.
I back to DroidFish 1.63, F-Droid deposit, and it's OK.

**Comment by Yky** [comment]
Could you provide a stacktrace of the error?

**Comment by reno-a** [comment]
How can I make it ?

**Comment by peterosterlund2** [comment]
Version 1.64 in the F-Droid repository is broken. You can use the google play version instead, or get a working version from here:

https://drive.google.com/drive/folders/0B0jy7CFOAmXrZ255bGhNdnZtc3M

I have no control over the F-Droid repository but I can confirm that it crashes with error "Can't read ECO database", which indicates that the F-Droid build scripts do not correctly handle this change:

https://github.com/peterosterlund2/droidfish/commit/ab601027b1a93731c98ac2560c450ba07ed8a4c8

**Comment by reno-a** [comment]
Hello,
Thank-you for your answer.
I don't have GApps and I use only F-Droid.
Maybe, you can (or, I can If you prefered) ask to F-Droid for look this?
Best regards.

**Comment by krt16s** [comment]
Sorry for the inconvenience, I disabled the build in https://gitlab.com/fdroid/fdroiddata/commit/2c74b2c7. I tried to build 1.65 with the eco.dat (thanks for pointing that out), but the resulting apk still is smaller (6.5 vs. 6.7 megs) and crashes at startup. The eco.dat is included and -- in fact -- identical:

````
sha1sum upstream/assets/eco.dat; sha1sum work/assets/eco.dat 
38f6b666c4292f4dd39bd9dc102536c511cdc5f2  upstream/assets/eco.dat
38f6b666c4292f4dd39bd9dc102536c511cdc5f2  work/assets/eco.dat
````

**Comment by peterosterlund2** [comment]
The problem is that I recently removed book.bin from git, since it is a generated file, but the F-Droid build script does not build it. I got it to work by tweaking build_binbook.xml and adding the following entry to org.petero.droidfish.txt:

Build:1.66,74
    commit=1b1977973a1c890836b3216fcde13de54475cd7d
    subdir=DroidFish
    prebuild=printf 'source.dir=src;../CuckooChessEngine/src' > ant.properties
    build=$$NDK$$/ndk-build && \
        ant -f build_copy_exe.xml && \
        ant release && \
        ant -f ../CuckooChessEngine/build_binbook.xml && \
        ant -f build_eco.xml && \
        ant release

**Comment by krt16s** [comment]
Thanks for having a look at it and making some changes, 1.66 should build fine tomorrow.

**Comment by reno-a** [comment]
Hello,
Today, I try the version 1.66 and it's OK.
Thank-you for all.
