### ISSUE TITLE
book.bin missing

### ISSUE THREAD

**Issue by ChristophHeilmann** [peterosterlund2/droidfish#12]
When I open the generated DroidFish.apk I can't find the book.bin in it.

**Comment by linhnv106** [comment]
I got the same problem, could you please help ? @ChristophHeilmann  @peterosterlund2

**Comment by ChristophHeilmann** [comment]
You can add the bin.book file  after you compiled the apk. Rename the .apk in .zip, open the .zip file with winrar and copy  the bin.book from the /git folder to the main directory. Afterwards you have to sign the .apk once again.
