### ISSUE TITLE
Can not build your project

### ISSUE THREAD

**Issue by linhnv106** [peterosterlund2/droidfish#16]
Hi, I'm trying to build your project but got this error :        
[java] Could not find org.petero.droidfish.buildtools.EcoBuilder. Make sure you have it in your classpath
 
in your build_eco.xml 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="build_eco" name="Build assets/eco.dat">
    <target name="build_eco">
        <java classpath="bin/classes"
              classname="org.petero.droidfish.buildtools.EcoBuilder">
            <arg value="${basedir}/src/org/petero/droidfish/buildtools/eco.pgn"/>  
            <arg value="${basedir}/assets/eco.dat"/>
        </java>
    </target>
</project>
but I cant find assets/eco.dat file, is that the problem ??

**Comment by peterosterlund2** [comment]
assets/eco.dat is the output file so it is expected that it does not exist if running EcoBuilder fails.
The launch configuration is in .externalToolBuilders/ECO_Builder.launch. It should be invoked automatically by eclipse. The compiled EcoBuilder class should be at workspace/droidfish/DroidFish/bin/classes/org/petero/droidfish/buildtools/EcoBuilder.class

**Comment by linhnv106** [comment]
when I imported the projects in eclipse. It does not recognize as android project, so it can't generate bin and gen folder . is there any missing config file ?

**Comment by linhnv106** [comment]
@peterosterlund2  I added project.property file and it works. but when I run on my device it got exception : 
 01-21 15:01:44.340: E/AndroidRuntime(10658): java.lang.RuntimeException: Can't read internal opening book
01-21 15:01:44.340: E/AndroidRuntime(10658): 	at org.petero.droidfish.book.InternalBook.initInternalBook(InternalBook.java:121)
 please help

**Comment by peterosterlund2** [comment]
project.properties is in git: https://github.com/peterosterlund2/droidfish/blob/master/DroidFish/project.properties

The exception indicates that build_binbook.xml and BinBook_Builder.launch for some reason failed to create CuckooChessEngine/{src,bin}/book.bin

**Comment by linhnv106** [comment]
@peterosterlund2 thank you very much. it works like a charm  . cheer!
