### ISSUE TITLE
Advance by one half move option

### ISSUE THREAD

**Issue by drsuser** [peterosterlund2/droidfish#18]
In the analysis mode, clicking on the left and right arrows always advances the game by a full move, i.e. at the end of black's half-move. This is a little jarring and makes it harder to enjoy following the game. It would be nice to have an option to advance by a half-move by clicking on the arrows.

**Comment by peterosterlund2** [comment]
This is explained in the hints section in the about/help dialog.

**Comment by drsuser** [comment]
Ah yes it is. Thanks!
