### ISSUE TITLE
tag releases for automatic f-droid updates

### ISSUE THREAD

**Issue by MartinNowak** [peterosterlund2/droidfish#23]
Atm. the missing git tags seem to require to manually find and add the commit hash to F-Droid's repo ([metadata/org.petero.droidfish.txt](https://gitlab.com/fdroid/fdroiddata/blob/d53270f2ff360840b55d7fa1be32d291a8809b72/metadata/org.petero.droidfish.txt)), with git tags this could be automated, leaving updates to a bot.

Would also allow to upload released apk's to GH releases, atm. they are only in the unmentioned [DroidFish – Google Drive](https://drive.google.com/drive/folders/0B0jy7CFOAmXrZ255bGhNdnZtc3M) folder (for backup reasons?).

Also see https://f-droid.org/docs/Build_Metadata_Reference/#Auto-Update-Mode

**Comment by peterosterlund2** [comment]
Done.
