### ISSUE TITLE
Format sources and layouts

### ISSUE THREAD

**Issue by ebraminio** [peterosterlund2/droidfish#37]
In order to make your reviews easier, is it possible for you to press Ctrl+Alt+L on all the layouts and java folders to format them? For my works on databinding it was necessary for me to format it to optimize imports and well other formatting options are also needed for better code readability. Even the fact it is one time job, it is also understandable to me if you don't like to do that for not breaking `git blame` thing, which, it won't break so much IMO and one can easily pass that but that's up to you to decided. Thanks!

**Comment by peterosterlund2** [comment]
I think the formatting is good as it is.
