### ISSUE TITLE
castling?

### ISSUE THREAD

**Issue by AaronM04** [peterosterlund2/droidfish#40]
How do I castle? I tried several things but nothing seems to work.

**Comment by peterosterlund2** [comment]
You castle by moving the king two steps towards the rook. A common mistake is that the castling flags were not set correctly when setting up a position.
When starting a new game, swipe from the right side of the screen and select new game from the menu.
When setting up a position, swipe from the left side of the screen and select castling flags to set what castling moves are available in the set up position.

**Comment by AaronM04** [comment]
That worked, thank you!

Is there a reason the castling flags were disabled by default?

**Comment by peterosterlund2** [comment]
They are not disabled by default. However, some people who have not found the "new game" menu item use "setup position" instead to restore the pieces to their original position after a game. In that case the castling flags were probably disabled during the game just played, and are not changed in setup mode unless the "castling flags" menu item is used.

**Comment by AaronM04** [comment]
The flags were disabled when I first came to that menu.

On May 13, 2019 10:05:41 AM PDT, "Peter Österlund" <notifications@github.com> wrote:
>They are not disabled by default. However, some people who have not
>found the "new game" menu item use "setup position" instead to restore
>the pieces to their original position after a game. In that case the
>castling flags were probably disabled during the game just played, and
>are not changed in setup mode unless the "castling flags" menu item is
>used.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/peterosterlund2/droidfish/issues/40#issuecomment-491906326

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by peterosterlund2** [comment]
Another possibility is that you moved your king or rooks, which would disallow future castling moves.

**Comment by AaronM04** [comment]
Ah, so if I move them and then start a new game a certain way, could it copy the flags (which would now be disabled)?

On May 13, 2019 10:48:27 AM PDT, "Peter Österlund" <notifications@github.com> wrote:
>Another possibility is that you moved your king or rooks, which would
>disallow future castling moves.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/peterosterlund2/droidfish/issues/40#issuecomment-491920656

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by peterosterlund2** [comment]
If you start a new game from the "new game" item in the right side menu, the flags are reset so that castling is allowed.

If you use the "edit board" function to manually put back all pieces on their original squares, you are not really starting a new game. In that case the castling flags would be the same as they were before you used the "edit board" function.

**Comment by AaronM04** [comment]
OK, I reinstalled the app and I was able to castle.

On May 13, 2019 10:57:03 AM PDT, "Peter Österlund" <notifications@github.com> wrote:
>If you start a new game from the "new game" item in the right side
>menu, the flags are reset so that castling is allowed.
>
>If you use the "edit board" function to manually put back all pieces on
>their original squares, you are not really starting a new game. In that
>case the castling flags would be the same as they were before you used
>the "edit board" function.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/peterosterlund2/droidfish/issues/40#issuecomment-491923571

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
