### ISSUE TITLE
The working directory is set to root when the engine starts

### ISSUE THREAD

**Issue by lealgo** [peterosterlund2/droidfish#41]
https://github.com/peterosterlund2/droidfish/blob/f95b64346252d7ade8598ddb3e6f8cac22d9391d/DroidFishApp/src/main/java/org/petero/droidfish/engine/ExternalEngine.java#L70-L77

Hi,
I'm testing some Android builds of the lc0 engine with DroidFish, and it's working fine. But the OpenCL back-end needs to create a tuning file for each network size, and it's failing to do so when loading with DroidFish. I'm trying with placing the tuner file in the current directory, as the engine doesn't have the Android context for a more adequate Context.getFilesDir(). The problem is that a call to `getcwd` from the engine returns the root directory (/) when loaded in DroidFish. This may or may not be a GUI issue, but is certainly a problem for the engines that create files, logs, and such. Or maybe I'm doing something wrong?

Regards,
Leandro

**Comment by peterosterlund2** [comment]
Hi,
Please test the latest version. It will set the working directory of the external engine process to DroidFish/uci/logs.

**Comment by lealgo** [comment]
> Hi,
> Please test the latest version. It will set the working directory of the external engine process to DroidFish/uci/logs.

It works perfectly! Thank you very much.
