### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by diabl0w** [peterosterlund2/droidfish#42]
Is there any documentation?

I cant figure out how to castle, there is another issue that was opened about opening a side menu but nothing in that menu says anything about castling.

 Also, what does the lightbulb button do cimpared to the M button > analysis mode button. Analysis mode doesn't seem to do anything but trigger analysis... it doesn't toggle any kind of mode. 

Lastly, I cant figure out how to turn off arrows, I dont want any hints of where to move.

**Comment by peterosterlund2** [comment]
I am working on a manual and hope to have the first version ready in a few days.

**Comment by peterosterlund2** [comment]
I have uploaded the first version of the manual now (README.md). Please let me know if you think anything is missing or unclear.
