### ISSUE TITLE
[Bug] Algebraic notation of game moves containing čech accents when "auto scroll move list" is checked in settings

### ISSUE THREAD

**Issue by MisesEnForce** [peterosterlund2/droidfish#44]
I reproduced the following bug on two different devices :

- Samsung Galaxy S9+ (SM-G965F (star2ltexx)) with lastest vanilla Android 9 update.
- Samsung Galaxy S10+ (SM-G975F (beyond2lteeea)) with latest vanilla Android 10 update.

with the same DroidFish (lastest version available) and DroidFish's configuration, meaning by that that same files in DroidFish's book, epd, ptb, pgn and uci folders are used.

I reproduced the following bug with all engines (lc0, stockfish 10, cuckoochess, stockfish 8 & 9, ethereal) and all opening books that I have (with almost all possible time configurations).

The bug is that when the "auto scroll move list" is checked in DroidFish's setting, DroidFish doesn't display all the moves of the game (which is intended) but then algebraic notations have čech accents :

![bad](https://user-images.githubusercontent.com/5349602/71764807-ee190c80-2eec-11ea-9c62-7b5108e08ef1.jpg)

**Comment by peterosterlund2** [comment]
It is not actually accents but the part of the preceding line that extends below the font baseline. This does not look good so I will fix it. Thanks for the report.

**Comment by peterosterlund2** [comment]
Fixed in version 1.78
