### ISSUE TITLE
Trouble importing OEX engines

### ISSUE THREAD

**Issue by lealgo** [peterosterlund2/droidfish#48]
I'd like to tell you about an issue I have while importing OEX engines on DroidFish. Using this template as a guide:

https://github.com/gkalab/chessenginesupport-androidlib/tree/master/StockfishChessEngine

I've built two packages, one unmodified with stockfish and the other with lc0. They both work well with other guis (Chess for Android and Chess PGN Master) but not with DroidFish. When I choose an OEX engine on the GUI I get an exception on `context.getContentResolver()`. I attach the exception.

![debug](https://user-images.githubusercontent.com/12534727/75847318-d48d2780-5dac-11ea-9c54-3e267da873e6.png)

![exception](https://user-images.githubusercontent.com/12534727/75847329-df47bc80-5dac-11ea-9f77-326a64fdd0c5.png)

Could it be something's missing from the Manifest?

_Originally posted by @lealgo in https://github.com/peterosterlund2/droidfish/issues/47#issuecomment-594331499_

**Comment by peterosterlund2** [comment]
It worked when I tried it. I built using gradle after adding automatic APK signing, see my forked repo.

Can you please send the compiled APK files to me so I can try to figure out what the problem is?

I know DroidFish is not using the latest ChessEngineResolver code but I hope the later changes have been made in a backwards compatible way.

**Comment by lealgo** [comment]
This is the package I used:

[stockfishChessEngine-debug.zip](https://github.com/peterosterlund2/droidfish/files/4289670/stockfishChessEngine-debug.zip)

It's unsigned I think, could this be the issue?

**Comment by peterosterlund2** [comment]
Your unsigned debug APK worked for me too. I tested on 3 different Android devices with versions 7.1.1, 8.1.1 and 9. What version of DroidFish are you using? Have you tried restoring version 1.79 from Google Play?

**Comment by lealgo** [comment]
Oh indeed! I've just tried with another phone and it worked. Maybe it's some issue with my dev. phone, a Huawei with Android 8. I'm using latest DF 1.79 from Google Play. Reinstalling and removing the DroidFish directory didn't fix it,  so I may try a factory reset later.

![Screenshot_20200304-170527](https://user-images.githubusercontent.com/12534727/75928378-45c7eb80-5e3c-11ea-9dd0-02681998d202.jpg)

**Comment by lealgo** [comment]
Well, I've factory-reset my phone and still get the same error. I can only speculate that something is broken with this Huawei Android version.

**Comment by lealgo** [comment]
Curious, this package works with DF:

https://play.google.com/store/apps/details?id=com.acidapestudios.chessenginescollection

But your Texel package does not work on DF, but it does with PGN Master.

![Screenshot_20200304-193601](https://user-images.githubusercontent.com/12534727/75936255-9e54b400-5e4f-11ea-91c4-e4c5ccd84313.jpg)

![Screenshot_20200304-193640](https://user-images.githubusercontent.com/12534727/75936263-a14fa480-5e4f-11ea-8a76-db48600e3078.jpg)

**Comment by lealgo** [comment]
This is even weirder, the acid ape engines that worked minutes ago, now they no longer work. But they still work on PGN Master.

![Screenshot_20200304-195819](https://user-images.githubusercontent.com/12534727/75937500-0e186e00-5e53-11ea-824e-a8f6308945d1.jpg)
![Screenshot_20200304-200322](https://user-images.githubusercontent.com/12534727/75937556-3c964900-5e53-11ea-9f10-8bc654ab3e8d.jpg)

**Comment by lealgo** [comment]
To summarize my results until now on my phone: I've tried with two OEX packages from Google Play, Texel's and Acid Ape's. All the engines work consistently with the app PGN Master, but with DroidFish the story is very different. On DF the Texel engine doesn't work at all, and Acid Ape's engines work after install, but then minutes later after I close and reopen DroidFish they fail, and then after a while they start to work again. When they fail the error is always the same as I reported above.

**Comment by lealgo** [comment]
Finally I could reproduce the issue. It seems that the overly aggressive task killer from Huawei is preventing the service to work. With the Acid Ape package I can work around it by opening their app, that just lists the engines installed. But for other gui-less packages like Texel and Droidfish I can't make it work.

**Comment by lealgo** [comment]
My question again is, why doesn't this happen with PGN Master? Maybe it's calling the service in a different way?

**Comment by lealgo** [comment]
Wow, the culprit was indeed Huawei's task killer. I've whitelisted the engine packages and now even Texel & Stockfish engines work on Droidfish with no issue.
