### ISSUE TITLE
Comiple SF for droidfsih

### ISSUE THREAD

**Issue by kandalto** [peterosterlund2/droidfish#51]
Hi Peter!

I would like to compile stockfish-dev for Droidfish. I've asked at stockfish github, but didn't get a comprehensive answer. Maybe you can give me some hints?

Cheers!

**Comment by peterosterlund2** [comment]
To compiled stockfish inside the DroidFish project you would have to copy the source code to the DroidFishApp/src/main/cpp/stockfish/ directory, then build the DroidFish project using gradle.
