### ISSUE TITLE
King's pawn opening gets stockfish in infinite loop

### ISSUE THREAD

**Issue by DoktorSultan** [peterosterlund2/droidfish#54]
Upon a king's pawn opening as white player, Stockfish keeps on thinking. I the messag droidfish is using lots of cpu and eventually my phone becomes warm...

Probably my battery drains fast too.

Isn't that a bit early in the game for a chess engine to become confused?

**Comment by peterosterlund2** [comment]
It does not happen when I try it. Maybe you have set a very long thinking time or have pondering enabled.

**Comment by DoktorSultan** [comment]
Yes, i changed some settings. I had everything on max.
I now changed a setting i cannot find again, something where you need to set a certain amount of moves... Unfortunately my game is in dutch. So i don't even know where to find pondering. Is it right there are 3 settings for the engine? Strength, hashtable size and 'peinzen' in dutch (thinking). Or is there more to find?

**Comment by peterosterlund2** [comment]
You can change the language from left drawer menu - settings - appearance - language. It's about half-way down the settings.

The time control is set from the first 3 settings: moves, time and increment. Changes will take effect when you start a new game.

Pondering is the fourth setting from the top.

**Comment by DoktorSultan** [comment]
Thanks, seems pondering is 'peinzen' in dutch. Now settings are better.
