### ISSUE TITLE
I cant Building DroidFish

### ISSUE THREAD

**Issue by WooDoo2** [peterosterlund2/droidfish#6]
I use Eclipse SDK  25.1.3 and NDK-r11c
I did everything as written in the instructions (wiki page)
When try native building? I have errors
make: **\* [obj/local/armeabi-v7a/objs/gtb/gtb-probe.o] Error 2
make: **\* [obj/local/armeabi-v7a/objs/gtb/gtb-dec.o] Error 2
Whats wrong. Help Please

Or you may add all the necessary (*.so) files in the libs folder

with android-ndk-r9d can building (with warning)
but when the application starts to Android device (5, 4.4) I got engine error armeabi v7a

I need help

**Comment by WooDoo2** [comment]
with android-ndk-r9d can building (with warning)
but when the application starts to Android device (5, 4.4) I got engine error armeabi v7a

**Comment by petermost** [comment]
Hi,

do these instructions https://github.com/petermost/droidfish/wiki help?

**Comment by WooDoo2** [comment]
Yes, I do everything on your instructions (but on windows)
Compiling with android-ndk-r10e-windows-x86_64, without errors
But when start apk I get message  "engine error stockfish-armeaby-v7a-nopie"

**Comment by petermost** [comment]
Please check the 'Native_Builder.log' and the 'copy_stockfish.log' file whether they contain any errors. Errors in the native build don't necessary show up in Eclipse.

**Comment by WooDoo2** [comment]
re-install windows, re-install last eclipse. Now compiling all ok.
Big thanks for you help
