### ISSUE TITLE
Android x86, big difference in performance between asmFish and Stockfish

### ISSUE THREAD

**Issue by jerry-green** [peterosterlund2/droidfish#7]
Performance of asmFish is about 2,5x time faster than Stockfish (DroidFish version) on Android x86.
Performance benchmarks you can see at https://jerrygreenblog.wordpress.com/2016/09/02/android-x86-asmfish-chess-engine/

Are you using some less agresive compilation switches for Stockfish ?

**Comment by peterosterlund2** [comment]
Stockfish in droidfish is compiled with aggressive compilation flags. The difference is probably a combination of 32 bit being slower than 64 bit and assembly generally being faster than C++.

**Comment by jerry-green** [comment]
Yes, i know 32b vs 64b, ASM vs. C++, but on the Windows 10 is difference only about 60%.
I was looking at  droidfish/DroidFish/jni/stockfish/Android.mk and there is -O2, it means that stockfish is compiled with this flag, if yes I would like to know why is not compiled with -O3 ?

If there is no change to compile Stockfish for  higher performance on Android, you can simply close this issue, it was more question than bug.

And thanks a lot for DroidFish.

**Comment by peterosterlund2** [comment]
Compiling with -O3 has not been an improvement in my tests. -flto did not help either. -fno-exceptions -fno-rtti is used by default for the android NDK.
