### ISSUE TITLE
toggle_arrows in res/values/strings.xml

### ISSUE THREAD

**Issue by aprijal-psrb** [peterosterlund2/droidfish#9]
"toggle_arrows" is not translated in "de" (German), "es" (Spanish), "fr" (French), "it" (Italian), "nl" (Dutch), 
 "pl" (Polish), "pt" (Portuguese), "ru" (Russian).

**Comment by peterosterlund2** [comment]
The language files have been updated. Not all texts have been translated though. If you want to help translating droidfish, please go to: https://crowdin.com/project/droidfish-android-chess-app
